ClienteApi/Models/LoanHistoryViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace ClienteApi.Models
{
    public class LoanHistoryViewModel
    {
        [Key]
        [DisplayName("Numero de Referencia")]
        public int IdLoansHistory { get; set; }

        [DisplayName("Tipo de Credito")]
        [Required(ErrorMessage = "El Credito es Requerido")]
        public int LoadId { get; set; }

        [DisplayName("Monto del Pago")]
        [Range(1, 9999999)]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        [Required(ErrorMessage = "El Monto del Pago es obligatorio")]
        public decimal PaymentAmount { get; set; }

        [DisplayName("Fecha de Pago")]
        [DataType(DataType.Date)]
        public DateTime PayDate { get; set; }

        [DisplayName("Tipo de Pago")]
        [Required(ErrorMessage = "El Tipo de Pago es Requerido")]
        public int PaymentType { get; set; }
    }
}

ClienteApi/Controllers/LoanController.cs
using ClienteAPI.Helpers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ClienteApi.Controllers
{
    public class LoanController : Controller
    {
        // GET: LoanController
        public ActionResult Index()
        {
            try
            {
                ServiceRepository serviceObj = new ServiceRepository();
                HttpResponseMessage response = serviceObj.GetResponse("api/Loan");
                HttpResponseMessage response2 = serviceObj.GetResponse("api/Customer");
                HttpResponseMessage response3 = serviceObj.GetResponse("api/LoansType");
                HttpResponseMessage response4 = serviceObj.GetResponse("api/Currency");
                HttpResponseMessage response5 = serviceObj.GetResponse("api/LoanState");

                response.EnsureSuccessStatusCode();
                response2.EnsureSuccessStatusCode();
                response3.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();

                var content = response.Content.ReadAsStringAsync().Result;
                var content2 = response2.Content.ReadAsStringAsync().Result;
                var content3 = response3.Content.ReadAsStringAsync().Result;
                var content4 = response4.Content.ReadAsStringAsync().Result;
                var content5 = response5.Content.ReadAsStringAsync().Result;

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<Models.LoanViewModel> loans = JsonConvert.DeserializeObject<List<Models.LoanViewModel>>(content);
                   
                    ViewBag.Customer = JsonConvert.DeserializeObject<List<Models.CustomerViewModel>>(content2);
                    ViewBag.LoansStype = JsonConvert.DeserializeObject<List<Models.LoanTypeViewModel>>(content3);
                    ViewBag.Currency = JsonConvert.DeserializeObject<List<Models.CurrencyViewModel>>(content4);
                    ViewBag.LoanState = JsonConvert.DeserializeObject<List<Models.LoanStateViewModel>>(content5);


                    if (TempData["exito"] != null)
                    {
                        ViewBag.exito = TempData["exito"];
                    }

                    if (TempData["error"] != null)
                    {
                        ViewBag.error = TempData["error"];
                    }

                    return View(loans);
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                {
                    TempData["error"] = "Hubo un error Interno no se pueden mostrar los creditos";

                    return RedirectToAction("Index", "Dashboard");
                }
                else
                {
                    TempData["error"] = "Hubo un error al Cargar los creditos";

                    return RedirectToAction("Index", "Dashboard");
                }
            }
            catch (Exception e)
            {

                TempData["error"] = "Hubo un error al Cargar los creditos";
                return RedirectToAction("Index", "Dashboard");

                throw;
            }
        }

        // GET: LoanController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                ServiceRepository serviceObj = new ServiceRepository();

                HttpResponseMessage response = serviceObj.GetResponse("api/Loan/" + id.ToString());
                HttpResponseMessage response2 = serviceObj.GetResponse("api/Customer");
                HttpResponseMessage response3 = serviceObj.GetResponse("api/LoansType");
                HttpResponseMessage response4 = serviceObj.GetResponse("api/Currency");
                HttpResponseMessage response5 = serviceObj.GetResponse("api/LoanState");

                response.EnsureSuccessStatusCode();
                response2.EnsureSuccessStatusCode();
                response3.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();

                var content = response.Content.ReadAsStringAsync().Result;
                var content2 = response2.Content.ReadAsStringAsync().Result;
                var content3 = response3.Content.ReadAsStringAsync().Result;
                var content4 = response4.Content.ReadAsStringAsync().Result;
                var content5 = response5.Content.ReadAsStringAsync().Result;

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    Models.LoanViewModel loans = response.Content.ReadAsAsync<Models.LoanViewModel>().Result;

                    ViewBag.Customer = JsonConvert.DeserializeObject<List<Models.CustomerViewModel>>(content2);
                    ViewBag.LoansStype = JsonConvert.DeserializeObject<List<Models.LoanTypeViewModel>>(content3);
                    ViewBag.Currency = JsonConvert.DeserializeObject<List<Models.CurrencyViewModel>>(content4);
                    ViewBag.LoanState = JsonConvert.DeserializeObject<List<Models.LoanStateViewModel>>(content5);

                    return View(loans);
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
                {
                    TempData["error"] = "Hubo un error al buscar los creditos";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Hubo un error al buscar los creditos";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["error"] = "Hubo un error al buscar los creditos";
                return RedirectToAction("Index");
                throw;
            }
        }

        // GET: LoanController/Create
        public ActionResult Create()
        {
            try
            {
                ServiceRepository serviceObj = new ServiceRepository();
                HttpResponseMessage response = serviceObj.GetResponse("api/LoansTypeInterest");
                HttpResponseMessage response2 = serviceObj.GetResponse("api/Customer");
                HttpResponseMessage response3 = serviceObj.GetResponse("api/LoansType");
                HttpResponseMessage response4 = serviceObj.GetResponse("api/Currency");
                HttpResponseMessage response5 = serviceObj.GetResponse("api/LoanState");

                response.EnsureSuccessStatusCode();
                response2.EnsureSuccessStatusCode();
                response3.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();
                response4.EnsureSuccessStatusCode();

                var content = response.Content.ReadAsStringAsync().Result;
                var content2 = response2.Content.ReadAsStringAsync().Result;
                var content3 = response3.Content.ReadAsStringAsync().Result;
                var content4 = response4.Content.ReadAsStringAsync().Result;
                var content5 = response5.Content.ReadAsStringAsync().Result;

                List<Models.LoansTypeInterestViewModel> loansTypeInterests = JsonConvert.DeserializeObject<List<Models.LoansTypeInterestViewModel>>(content);
                ViewBag.CustomerViewModel = JsonConvert.DeserializeObject<List<Models.CustomerViewModel>>(content2);
                ViewBag.LoansStype = JsonConvert.DeserializeObject<List<Models.LoanTypeViewModel>>(content3);
                ViewBag.Currency = JsonConvert.DeserializeObject<List<Models.CurrencyViewModel>>(content4);
                ViewBag.LoanState = JsonConvert.DeserializeObject<List<Models.LoanStateViewModel>>(content5);
                ViewBag.TypeInterests = loansTypeInterests;


                return View();
            }
            catch (Exception e) 
            {
                return RedirectToAction("Index");
            }
        }

        // POST: LoanController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int tiempo,Models.LoanViewModel loan)
        {
            try
            {
                loan.StarDate = DateTime.Now;
                loan.NextDueDate = DateTime.Now.AddMonths(1);
                loan.CurrentAmount = (loan.LoanAmount * (1 + (loan.InteresRate/100))) + loan.BankFees;
                loan.MonthlyAmount = (loan.CurrentAmount / (tiempo*12));
                loan.EndDate = DateTime.Now.AddYears(tiempo);
                loan.IdLoansState = 1;


                ServiceRepository serviceObj = new ServiceRepository();
                HttpResponseMessage response = serviceObj.PostResponse("api/Loan", loan);
                response.EnsureSuccessStatusCode();


                if (response.StatusCode == System.Net.HttpStatusCode.Created)
                {
                    TempData["exito"] = "Se creado el Credito con exito";

                    return RedirectToAction("Index");
                }
                else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    ViewBag.error = "Hubo un error al crear el Credito";
                    return View();
                }
                else
                {
                    ViewBag.error = "Hubo un error al crear el Credito";
                    return View();
                }

            }
            catch
            {
                ViewBag.error = "Hubo un error al crear el Credito";
                return View();
            }
        }

        // GET: LoanController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                ServiceRepository serviceObj = new ServiceRepository();

                HttpResponseMessage response = serviceObj.GetResponse("api/Loan/" + id.ToString());

ClienteApi/Views/LoanHistory/Create.cshtml
@using ClienteApi.Models;
@model ClienteApi.Models.LoanHistoryViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    List<SelectListItem> contentData = new List<SelectListItem>();
    foreach (PaymentTypeViewModel paymentType in ViewBag.PaymentType)
    {
        contentData.Add(new SelectListItem {
                    Text = paymentType.PaymentTypeName,
                    Value = paymentType.IdPaymentType.ToString(),
        });
    }

}


@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.exito</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.error</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #007BFF;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Creacion de un Pago</h2>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-horizontal">
                <div class="form-group">

                    <div class="col-md-10 mt-3">
                        <label class="text-dark">
                            <span>
                                <label>Credito #</label>
                            </span>
                        </label>
                        <input class="form-control" value="FIDE000-@ViewBag.loanId" disabled />
                        <input hidden asp-for="LoadId" class="form-control" value="@ViewBag.loanId" />
                        <span asp-validation-for="LoadId" class="text-danger"></span>
                    </div>

                    <div class="col-md-10 mt-3">
                        <label class="text-dark">
                            <span>
                                <label asp-for="PaymentAmount" class="control-label"></label>
                            </span>
                        </label>
                        <input asp-for="PaymentAmount" class="form-control" type="number"/>
                        <span asp-validation-for="PaymentAmount" class="text-danger"></span>
                    </div>

                    @* 
                    <div class="col-md-10 mt-3">
                        <label class="text-dark">
                            <span>
                                <label asp-for="PayDate" class="control-label"></label>
                            </span>
                        </label>
                        @{
                            String date = DateTime.Now.ToString("dd/MM/yyyy");
                        }
                        <input asp-for="PayDate" class="form-control" value="@date"  disabled />
                        <span asp-validation-for="PayDate" class="text-danger"></span>
                    </div>

                    <div class="col-md-10 mt-3">
                        <label class="text-dark">
                            <span>
                                <label asp-for="PaymentType" class="control-label"></label>
                            </span>
                        </label>
                        <select class="form-select" id="IdCountry" asp-for="PaymentType" asp-items="@contentData">
                            <option selected>Seleccione un Tipo de Pago</option>
                        </select>
                        <span asp-validation-for="PaymentType" class="text-danger"></span>
                    </div>
                    *@

                    <div class="form-group mt-5">
                        <input type="submit" value="Pagar" class="btn btn-primary" />
                    </div>

                </div>
            </div>
        </form>
        <div>
            <a asp-action="Index", asp-controller="Loan">Volver al Listado de Creditos</a>
        </div>
    </div>



</div>

ClienteApi/Views/LoanHistory/Edit.cshtml
@using ClienteApi.Models;
@model ClienteApi.Models.LoanHistoryViewModel

@{
    ViewData["Title"] = "eDITAR pAGO ";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

    String paymentName = "";

    foreach (PaymentTypeViewModel paymentType in ViewBag.PaymentType)
    {
        if (paymentType.IdPaymentType == Model.PaymentType) 
        {
            paymentName = paymentType.PaymentTypeName;
        }
    }

}


@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.exito</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.error</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}

<div class="card-body card shadow mb-4">
    <style>
        .card-title {
            padding-bottom: 15px;
            background: #040FD9;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }
    </style>
    <div class="card-title">
        <div class="row">
            <div class="col-sm-6">
                @{
                    String payName = "FIDE0000" + Model.LoadId + "-00" + Model.IdLoansHistory;
                }
                <h2>Editar el Pago # @payName </h2>
            </div>
        </div>
    </div>

    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
        <input asp-for="IdLoansHistory" class="form-control" hidden/>

        <input asp-for="LoadId" class="form-control" hidden />

        <input asp-for="PayDate" class="form-control" hidden />

        <input asp-for="PaymentType" class="form-control" hidden/>

        <div class="col-md-10 mt-3">
            <label class="text-dark">
                <strong>
                    <label asp-for="PaymentAmount" class="control-label"></label>
                </strong>
            </label>
            <input asp-for="PaymentAmount" class="form-control" />
            <span asp-validation-for="PaymentAmount" class="text-danger"></span>
        </div>

        <div class="col-md-10 mt-3">
            <label class="text-dark">
                <strong>
                    <label asp-for="PaymentType" class="control-label"></label>
                </strong>
            </label>
            <input value="@paymentName" class="form-control" disabled />
        </div>


        <div class="form-group mt-5">
            <input type="submit" value="Actualizar Pago" class="btn btn-primary" />
        </div>
        
    </form>

    <div>
        <a asp-action="Index" asp-controller="Loan">Volver a los Creditos</a>
    </div>

</div>

ClienteApi/Views/LoanHistory/IndexDetail.cshtml
@using ClienteApi.Models;
@model IEnumerable<ClienteApi.Models.LoanHistoryViewModel>

@{
    ViewData["Title"] = "IndexDetail";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@if (ViewBag.exito == "" | ViewBag.exito == null)
{

}
else
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.exito</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}
@if (ViewBag.error == "" | ViewBag.error == null)
{

}
else
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <span class="aria-hidden">@Html.ViewBag.error</span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>

}

@{
    LoanViewModel thisLoanInfo = new LoanViewModel();
    String currencySymbol = "";

    if (Model.Count() >= 1) 
    {
        foreach (LoanViewModel loan in ViewBag.Loans)
        {
            if (loan.IdLoan == Model.First().LoadId)
            {
                thisLoanInfo = loan;
            }
        }
    }

    foreach (CurrencyViewModel currency in ViewBag.Currency)
    {
        if (currency.IdCurrencies == thisLoanInfo.IdCurrencies)
        {
            currencySymbol = currency.Symbol;
        }
    }
}

<div class="card-body card shadow mb-4">
    <style>
        .table-title {
            padding-bottom: 15px;
            background: #007BFF;
            color: #fff;
            padding: 16px 30px;
            min-width: 100%;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

            .table-title h2 {
                margin: 5px 0 0;
                font-size: 24px;
            }

            .table-title .btn-group {
                float: right;
            }

            .table-title .btn {
                float: right;
                font-size: 13px;
                border: none;
                min-width: 50px;
                border-radius: 2px;
                border: none;
                outline: none !important;
                margin-left: 10px;
            }
    </style>

    <div class="table-title">
        <div class="row">
            <div class="col-sm-6">
                <h2>Credito #FIDE000-@ViewBag.LoanId</h2>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-dark btn-lg" asp-action="Create">Crear un Pago</a>
            </div>
        </div>
    </div>
    <div class="table-responsive table-hover">
        <table id="TableEmployee" class="table table-avance table-striped " cellspacing="0" width="100%">
            <thead class="table-primaryk">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdLoansHistory)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LoadId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentAmount)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PayDate)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PaymentType)
                    </th>
                    <th>
                        Opciones
                    </th>
                </tr>

            </thead>
            <tbody class=" ">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @{
                                int id = item.IdLoansHistory;
                                String thisHistory = item.IdLoansHistory.ToString();
                                String numReferen = "FIDE0000" + @thisLoanInfo.IdLoan + "-00" + thisHistory;
                            }
                            @numReferen
                        </td>
                        <td>
                            @thisLoanInfo.LoansDescription
                            @*Html.DisplayFor(modelItem => item.LoadId)*@
                        </td>
                        <td>
                            @currencySymbol
                            @Html.DisplayFor(modelItem => item.PaymentAmount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PayDate)
                        </td>
                        <td>
                            @foreach (PaymentTypeViewModel paymentType in ViewBag.PaymentType)
                            {
                                if (paymentType.IdPaymentType == item.PaymentType)
                                {
                                    @Html.DisplayFor(modelItem => paymentType.PaymentTypeName)
                                }
                            }
                        </td>
                        <td>
                            @Html.ActionLink("Editar Pago", "Edit", new {  id=item.IdLoansHistory  } , new { @class = "btn btn-primary " })
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal-@item.IdLoansHistory">
                                Eliminar
                            </button>
                        </td>
                    </tr>
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal-@item.IdLoansHistory" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">
                                        <i class="fas fa-exclamation-triangle" style="color:red;"></i>
                                        Advertencia
                                    </h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Esta Seguro que desea Eliminar el Pago con Numero de Referencia @numReferen ?
                                </div>
                                <div class="modal-footer">

                                    <form asp-action="Delete" asp-route-id="@item.IdLoansHistory" >
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                        <input type="submit" value="Eliminar" class="btn btn-danger" />
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                }

            </tbody>

        </table>

    </div>

     <div class="mt-4">
        <a asp-action="Index" asp-controller="Loan">Volver a los Creditos</a>
    </div>


</div>